runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: _go_app

nobuild_files: vendor/
env_variables:
  DATABASE_NAME: ''
  CLOUDSQL_CONNECTION_NAME: ''
  CLOUDSQL_USER: ''
  CLOUDSQL_PASSWORD: ''
  DB_CONNECTION_NAME: ''
  DB_USER: ''
  DB_PASSWORD: ''